### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [sem-geologist/qgis-element-table#1]
# Problem
Can you please add 
![hpp](https://user-images.githubusercontent.com/2510900/106750071-039cc080-6630-11eb-9e66-6d43bb8b10bc.png)

**Comment by sem-geologist** [comment]
@NyakudyaA , I am sorry I can't understand what should I add? Is that "homepage" which is not required? Indeed, I plan to add the homepage, (probably gh_pages), but currently  I want to see if this has any potential to be added to repository. Please elaborate, what exactly is missing.

**Comment by sem-geologist** [comment]
... and to be honest, I feel much more fluent in python/PyQt than in html/css/js. Making a nice homepage looks more challenging than making a functional plugin for QGIS.

**Comment by sem-geologist** [comment]
I could add link to README.md as that  provides more information on the plugin. @NyakudyaA , would that currently be enough?

**Comment by NyakudyaA** [comment]
Hi @sem-geologist , Just add a homepage link in metadata.txt linking it to the same github repo. It doesn't have to be a HTML page

**Comment by sem-geologist** [comment]
I had edited that in https://plugins.qgis.org/plugins/my metadata GUI form, and here. Should I re-upload with fix, or metadata.txt is updated  automatically after changing fields in a form?

**Comment by NyakudyaA** [comment]
LGTM approved
